Repository menloresearch/cortex.cpp, pull requests merged in 2023-11, with the labels that each got.

#98 Nitron linux allow all cors for cloud-native
  .github/workflows/build.yml
Labels: type: ci

#122 Unload model stop background
  controllers/llamaCPP.cc
  controllers/llamaCPP.h
Labels: P0: critical

#144 Add c/c++ file extension trigger for nitro CI
  .github/workflows/build.yml
Labels: type: ci, type: chore

#155 chore: enable-mermaid
  docs/docusaurus.config.js
  docs/package.json
  docs/yarn.lock
Labels: type: chore

#156 CloudFlare Pages add Preview URL to PR
  .github/workflows/build.yml
  .github/workflows/docs.yml
Labels: type: feature request

#171 Add tar gz to nitro release and add docs publish instruction to README.md docs
  .github/workflows/build.yml
  docs/README.md
Labels: type: enhancement

#172 feat: improvements on nitro landing page
  docs/src/containers/DownloadButton/index.js
  docs/src/containers/GithubButton/index.js
  docs/src/containers/Homepage/Architecture/index.js
  docs/src/containers/Homepage/OpenAI/index.js
  docs/src/containers/Homepage/Statistic/index.js
  docs/src/pages/index.js
  docs/static/img/favicon.ico
  docs/static/img/logos/apple-logo-white.png
  docs/static/img/logos/linux-logo-white.png
  docs/static/img/logos/llamacpp.svg
  docs/static/img/logos/nvdia.svg
  docs/static/img/logos/stable-diffusion.svg
  docs/static/img/logos/whispercpp.svg
  docs/static/img/logos/windows-logo-white.png
Labels: type: feature request

#177 feat(example): Add openai integration with nitro
  docs/docs/examples/openai-node.md
  docs/docs/examples/openai-python.md
  docs/sidebars.js
Labels: P1: important, type: documentation, type: enhancement

#180 Revert docs CICD trigger on push to main instead of tag-based
  .github/workflows/docs.yml
Labels: type: ci, type: chore

#181 Update docs
  docs/docs/demos/chatbox-vid.mdx
  docs/docs/examples/chatbox.md
  docs/docs/examples/jan.md
  docs/docs/examples/llm.md
  docs/docs/new/about.md
  docs/docs/new/build-source.md
  docs/sidebars.js
Labels: P1: important, type: documentation

#182 feat: change the preview image of nitro landing page
  docs/static/img/nitro-social-card.png
Labels: type: feature request

#191 chore: upgrade all packages in docs
  docs/package.json
  docs/yarn.lock
Labels: type: chore

#197 bug: fix the model loaded result in error
  controllers/llamaCPP.cc
Labels: type: bug

#200 bug: should be responsive and stacking up on mobile
  docs/docs/features/chat.md
  docs/docs/features/embed.md
  docs/docs/new/about.md
  docs/src/styles/components/base.scss
  docs/src/styles/tweaks/sidebar.scss
Labels: type: bug

#220 Deprecate nitro.zip
  .github/workflows/build.yml
  docs/src/containers/DownloadButton/index.js
  docs/src/containers/Homepage/GetNitro/index.js
  examples/example-docker/Dockerfile
  install.bat
  install.sh
Labels: type: chore
