Repository menloresearch/cortex.cpp, pull requests merged in 2023-12, with the labels that each got.

#222 Add nightly build ci
  .github/workflows/build.yml
Labels: type: chore

#228 Correct condition for nighty build to trigger noti-discord
  .github/workflows/build.yml
Labels: type: ci

#232 Add document for nightly build and update message for manual build
  .github/workflows/build.yml
  README.md
Labels: type: chore

#233 Add windows codesign for nitro
  .github/workflows/build.yml
Labels: type: chore

#252 251 feat periodically clean cache
  README.md
  controllers/llamaCPP.cc
  controllers/llamaCPP.h
Labels: P0: critical

#253 feat: CI Add packaging job for cudart runtime
  .github/workflows/build.yml
Labels: P1: important, type: enhancement, type: ci

#257 Nightly build update URL in README.md file
  .github/workflows/build.yml
  .github/workflows/update-release-url.yml
  README.md
Labels: type: ci, type: chore

#258 Add icon for table download README
  README.md
  docs/static/img/linux.png
  docs/static/img/mac.png
  docs/static/img/windows.png
Labels: type: chore

#261 Fix/ci autobump
  .github/workflows/auto-bump-llamacpp.yml
  .github/workflows/build.yml
Labels: type: ci

#274 Fix error nitro GPU run failed on linux
  .github/workflows/build.yml
Labels: type: bug, type: ci

#239 feat: improve SEO for nitro
  docs/docs/examples/jan.md
  docs/docs/examples/openai-node.md
  docs/docs/examples/openai-python.md
  docs/docs/examples/palchat.md
  docs/docs/features/chat.md
  docs/docs/features/cont-batch.md
  docs/docs/features/embed.md
  docs/docs/features/feat.md
  docs/docs/features/load-unload.md
  docs/docs/features/multi-thread.md
  docs/docs/features/prompt.md
  docs/docs/features/warmup.md
  docs/docs/new/about.md
  docs/docs/new/architecture.md
  docs/docs/new/build-source.md
  docs/docs/new/faq.md
  docs/docs/new/install.md
  docs/docs/new/model-cycle.md
  docs/docs/new/quickstart.md
  docs/docusaurus.config.js
  docs/static/robots.txt
Labels: type: enhancement

#288 feat: add more threads for core services
  controllers/llamaCPP.cc
  main.cc
Labels: P0: critical

#291 feat: Add Github CodeQL
  .github/workflows/auto-bump-llamacpp.yml
  .github/workflows/codeql-analysis.yml
  controllers/health.h
  controllers/llamaCPP.cc
  controllers/processManager.cc
  controllers/processManager.h
Labels: P2: nice to have, type: ci, type: chore

#293 fix: update assets cross cpu
  docs/static/img/platforms/cross-cpus.svg
Labels: type: chore

#294 290 feat proper threadpool allocations
  controllers/llamaCPP.cc
  main.cc
Labels: P0: critical

#300 124 feat add flag for nitro version build with cmake example dnitro version
  CMakeLists.txt
  main.cc
Labels: P0: critical
