Repository menloresearch/cortex.cpp, pull requests merged in 2023-10, with the labels that each got.

#44 CUDA support for Nitro on amd64 - linux
  CMakeLists.txt
  controllers/llamaCPP.cc
  controllers/llamaCPP.h
  controllers/nitro_utils.h
Labels: P0: critical

#53 42 add health check path in api
  controllers/health.cc
  controllers/health.h
Labels: P0: critical

#65 37 api with llamacpp for embedding
  config.json
  controllers/llamaCPP.cc
  controllers/llamaCPP.h
Labels: P0: critical

#70 Refactor CICD: change trigger by tag and add release note template
  .github/release-drafter.yml
  .github/workflows/build.yml
Labels: type: ci, type: chore

#71 Fix error release name in release drafter template
  .github/release-drafter.yml
  .github/workflows/build.yml
Labels: type: ci

#64 feat: CI/CD and windows with/ without GPU
  .github/workflows/build.yml
Labels: P0: critical

#87 Correct robocopy command
  .github/workflows/build.yml
Labels: type: ci

#95 Simple e2e testing for nitro binary file
  .github/scripts/e2e-test-linux-and-mac.sh
  .github/scripts/e2e-test-windows.bat
  .github/workflows/build.yml
Labels: type: feature request, type: ci
