Repository menloresearch/cortex.cpp, pull requests merged in 2024-05, with the labels that each got.

#582 Feat cicd cortex js+ code signing for cortex cpp
  .github/workflows/cortex-cpp-build.yml
  .github/workflows/cortex-cpp-quality-gate.yml
  .github/workflows/cortex-js.yml
  cortex-cpp/Makefile
  cortex-js/package.json
  package.json
Labels: type: feature request

#583 Add path for dotnet tool windows code signing step
  .github/workflows/cortex-cpp-build.yml
Labels: type: bug, type: ci

#597 replace deprecated ci step
  .github/pull_request_template.md
  .github/workflows/cortex-cpp-build.yml
Labels: type: chore

#611 Add cpuinfo to help check cpu instruction
  cortex-js/cpuinfo/README.md
  cortex-js/cpuinfo/bin/cpuinfo
  cortex-js/cpuinfo/bin/cpuinfo.exe
  cortex-js/cpuinfo/src/CPUID.h
  cortex-js/cpuinfo/src/cpuinfo.cpp
  cortex-js/cpuinfo/src/example.json
  cortex-js/package.json
Labels: type: feature request

#591 API: added the API reference decorator
  cortex-js/package-lock.json
  cortex-js/src/infrastructure/controllers/assistants.controller.ts
  cortex-js/src/infrastructure/controllers/chat.controller.ts
  cortex-js/src/infrastructure/controllers/cortex.controller.ts
  cortex-js/src/infrastructure/controllers/messages.controller.ts
  cortex-js/src/infrastructure/controllers/models.controller.ts
  cortex-js/src/infrastructure/controllers/threads.controller.ts
  cortex-js/src/infrastructure/dtos/assistants/assistant-tool.dto.ts
  cortex-js/src/infrastructure/dtos/assistants/create-assistant.dto.ts
  cortex-js/src/infrastructure/dtos/assistants/delete-assistant.dto.ts
  cortex-js/src/infrastructure/dtos/chat/chat-completion-message.dto.ts
  cortex-js/src/infrastructure/dtos/chat/chat-completion-response.dto.ts
  cortex-js/src/infrastructure/dtos/chat/choice.dto.ts
  cortex-js/src/infrastructure/dtos/chat/create-chat-completion.dto.ts
  cortex-js/src/infrastructure/dtos/chat/message.dto.ts
  cortex-js/src/infrastructure/dtos/chat/usage.dto.ts
  cortex-js/src/infrastructure/dtos/cortex/cortex-operation-successfully.dto.ts
  cortex-js/src/infrastructure/dtos/cortex/start-cortex.dto.ts
  cortex-js/src/infrastructure/dtos/messages/content-value.dto.ts
  cortex-js/src/infrastructure/dtos/messages/create-message.dto.ts
  cortex-js/src/infrastructure/dtos/messages/delete-message.dto.ts
  cortex-js/src/infrastructure/dtos/messages/get-message.dto.ts
  cortex-js/src/infrastructure/dtos/messages/list-message.dto.ts
  cortex-js/src/infrastructure/dtos/messages/thread-content.dto.ts
  cortex-js/src/infrastructure/dtos/models/create-model.dto.ts
  cortex-js/src/infrastructure/dtos/models/delete-model.dto.ts
  cortex-js/src/infrastructure/dtos/models/download-model.dto.ts
  cortex-js/src/infrastructure/dtos/models/list-model-response.dto.ts
  cortex-js/src/infrastructure/dtos/models/model-artifact.dto.ts
  cortex-js/src/infrastructure/dtos/models/model-metadata.dto.ts
  cortex-js/src/infrastructure/dtos/models/model-runtime-params.dto.ts
  cortex-js/src/infrastructure/dtos/models/model-setting-params.dto.ts
  cortex-js/src/infrastructure/dtos/models/model-successfully-created.dto.ts
  cortex-js/src/infrastructure/dtos/models/start-model-success.dto.ts
  cortex-js/src/infrastructure/dtos/threads/create-thread-assistant.dto.ts
  cortex-js/src/infrastructure/dtos/threads/create-thread-model-info.dto.ts
  cortex-js/src/infrastructure/dtos/threads/create-thread.dto.ts
  cortex-js/src/infrastructure/dtos/threads/delete-thread.dto.ts
  cortex-js/src/infrastructure/dtos/threads/get-thread.dto.ts
  cortex-js/src/main.ts
Labels: P1: important
