Repository menloresearch/cortex.cpp, pull requests merged in 2024-10, with the labels that each got.

#1436 Reorganize README.md - move beta, nightly, network installer to bottom)
  README.md
Labels: type: docs

#1466 fix: update link editurl field docs
  docs/docusaurus.config.ts
Labels: type: bug

#1561 fix: broken api-reference page
  docs/docusaurus.config.ts
Labels: type: bug

#1549 chore: copy edits
  docs/docs/cli/cortex.mdx
  engine/cli/command_line_parser.cc
  engine/cli/commands/cortex_upd_cmd.cc
  engine/cli/commands/ps_cmd.cc
  engine/controllers/swagger.cc
Labels: category: app shell, type: chore
