Repository menloresearch/cortex.cpp, pull requests merged in 2024-01, with the labels that each got.

#302 Add nitro version flag to ci
  .github/workflows/build.yml
Labels: type: ci, type: chore

#311 310 bug cannot unload model on nitro 022
  CMakeLists.txt
  controllers/llamaCPP.h
Labels: P0: critical

#315 Feature nitro distribution
  .github/runners/actions-runner-ubuntu-cuda-11-4.dockerfile
  .github/runners/actions-runner-ubuntu-cuda-12-0.dockerfile
  .github/runners/actions-runner-windows-cuda-11-4.dockerfile
  .github/runners/actions-runner-windows-cuda-12-0.dockerfile
  .github/runners/runner.ps1
  .github/runners/start.sh
  .github/workflows/build.yml
Labels: P0: critical, type: bug

#326 fix: Remove -DDEBUG=ON
  .github/workflows/build.yml
Labels: type: ci

#329 feat: add manually specified log folder
  controllers/llamaCPP.cc
  controllers/llamaCPP.h
Labels: P0: critical

#332 feat: add condition to not emit log file if there is no path to log f…
  controllers/llamaCPP.cc
  controllers/llamaCPP.h
Labels: P0: critical

#334 Fix upgrade cuda to 11.7
  .github/runners/actions-runner-ubuntu-cuda-11-7.dockerfile
  .github/runners/actions-runner-ubuntu-cuda-12-0.dockerfile
  .github/runners/actions-runner-windows-cuda-11-7.dockerfile
  .github/runners/actions-runner-windows-cuda-12-0.dockerfile
  .github/workflows/build.yml
Labels: type: bug

#337 Switch building nitro windows cpu to github windows-latest to fix bit defender warning
  .github/workflows/build.yml
Labels: P0: critical, type: bug

#340 chore: Add ci change for folder exclusion
  .github/workflows/codeql-analysis.yml
Labels: type: ci

#342 313 bug busy waiting is causing cpu usage
  controllers/llamaCPP.cc
  controllers/llamaCPP.h
Labels: P0: critical

#333 Feat: Update documentation
  docs/docs/examples/chatboxgpt.md
  docs/docs/examples/img/chatgptbox_cus.png
  docs/docs/examples/img/chatgptbox_menu.png
  docs/docs/examples/img/chatgptbox_use.png
  docs/docs/examples/palchat.md
  docs/docs/features/log.md
  docs/docs/features/vision.md
  docs/sidebars.js
Labels: P2: nice to have, type: chore

#357 215 epic queue system
  controllers/llamaCPP.cc
  controllers/llamaCPP.h
Labels: P1: important

#356 Documentation 0.2.10
  README.md
  docs/docs/examples/chatboxgpt.md
  docs/docs/features/grammar.md
  docs/docs/features/load-unload.md
  docs/docs/features/multi-thread.md
  docs/docs/features/self-extend.md
  docs/sidebars.js
Labels: P1: important, type: documentation, type: chore

#380 add checking model loaded first in embedding call
  controllers/llamaCPP.cc
Labels: P1: important

#388 remove model folder feature
  controllers/llamaCPP.h
Labels: P1: important

#392 391 bug stream toggle off takes forever to respond
  controllers/llamaCPP.cc
Labels: P0: critical

#398 bug: correct way of handle grammar file
  controllers/llamaCPP.cc
Labels: P0: critical
